---
blank_issues_enabled: false
contact_links:
  - name: Community (such as matrix.org, Revolt & Discord)
    url: https://github.com/MartinEesmaa/VVCEasy#community
    about: >
      If you need an extra little help and wanted to be helped by anyone, 
      you can join one of my server on matrix.org, Revolt or Discord.