name: .NET

on:
  push:
    paths:
    - 'Program.cs'
  pull_request:
    paths: 
    - 'Program.cs'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build VVCEasy (.NET Console Version)
      run: dotnet build --no-restore
    - name: Test VVCEasy (.NET Console Version)
      run: dotnet test --no-build --verbosity normal
